# Generated by Django 4.2.4 on 2023-08-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=225, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='remark/image')),
                ('client_remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='is_popular',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
