# Generated by Django 4.2.4 on 2023-08-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_remark_item_is_popular'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
    ]
