# Generated by Django 4.2.4 on 2023-09-08 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('ecom', '0003_rename_ordered_at_order_ordered_at_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customer'),
        ),
    ]
