# Generated by Django 4.2.4 on 2023-08-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_rename_item_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='product',
        ),
    ]
