# Generated by Django 4.2.4 on 2023-09-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_paymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='paystack_access_code',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='paystack_charge_id',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='ref',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
