# Generated by Django 4.2.4 on 2023-09-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_remove_paymenthistory_paystack_access_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='ref',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='paystack_access_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='paystack_charge_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
