# Generated by Django 4.2.4 on 2023-09-28 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_remove_paymenthistory_paystack_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
